server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sangcheol12/MSA_sample
          #username: git username
          #password: git password